# Generated by Django 4.0.5 on 2022-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myprofile', models.ImageField(blank=True, default='/static/ge.jpg', null=True, upload_to='images/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
